require("./Units/storelocal.spec");
require("./Units/conectDB.spec");
require("./Units/crypt.spec");
require("./Units/faker.spec");
require("./Units/uuid.spec");
require("./Units/jwt.spec");
require("./Integrations/users.spec");
require("./Integrations/sessions.spec");
require("./Integrations/authuser.spec");
